project_id = "ncwsvchxohbvthjmefmh"

[functions.og-proxy]
verify_jwt = false

[functions.admin-db]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.temp-update]
verify_jwt = false
